### ISSUE TITLE
Konačno!

### ISSUE THREAD

**Issue by cvladan** [ICEF-NLP/COMtext.SR#1]
... tek danas sam slučajno otkrio da je skoro pokrenut ovaj projekat.
Sve što imam da kažem je - **Konačno!**

#### A u međuvremenu

Ne znam spada li ovde ovakva informacija, ali ako postoje zainteresovani, molim vas da doprinesemo internacionalnim AI projektima koji na neki način podržavaju srpski jezik, a kojih i nema mnogo. Na primer:

1. [Common Voice](https://commonvoice.mozilla.org/sr)
1. [Common Voice Sentence Collector](https://commonvoice.mozilla.org/sentence-collector/#/sr)
1. [Home Assistant Voice](https://developers.home-assistant.io/docs/voice/intent-recognition/supported-languages/)

**Comment by tsamardzic** [comment]
Hvala puno na podršci! 

Prepoznavanje govora nije direktno vezano za ovaj repozitorijum ali jeste u domenu aktivnosti ReLDI Centra. 

Nedavno smo sa CLARIN.SI objavili jedan set podataka za srpski pod vrlo slobodnom licencom: https://www.clarin.si/repository/xmlui/handle/11356/1679

**Comment by cvladan** [comment]
> Hvala puno na podršci!
> 
> Prepoznavanje govora nije direktno vezano za ovaj repozitorijum ali jeste u domenu aktivnosti ReLDI Centra.
> 
> Nedavno smo sa CLARIN.SI objavili jedan set podataka za srpski pod vrlo slobodnom licencom: https://www.clarin.si/repository/xmlui/handle/11356/1679

Da da, već video.

Možda ga dodati na [sentence collector](https://commonvoice.mozilla.org/sentence-collector/#/sr) pošto jedini, onaj stari, uglavnom samo o ratu u BiH :(
